I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter 3.rpy", line 38, in script
    if amigo:
  File "game/chapter 3.rpy", line 38, in <module>
    if amigo:
NameError: name 'amigo' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter 3.rpy", line 38, in script
    if amigo:
  File "E:\renpy-8.3.6-sdk\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "E:\renpy-8.3.6-sdk\renpy\python.py", line 1215, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\renpy-8.3.6-sdk\renpy\python.py", line 1208, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chapter 3.rpy", line 38, in <module>
    if amigo:
NameError: name 'amigo' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.6.25022803
Vampire 1.0
Wed Jun  4 22:43:06 2025
